### ISSUE TITLE
Set branch rules

### ISSUE THREAD

**Issue by shannonhlo** [shannonhlo/pokemon_classification#2]
- protect main branch
- require code review before merging

**Comment by gavh3** [comment]
I think since you're the repository admin only you can do this @shannonhlo

**Comment by shannonhlo** [comment]
Tested branch protection rules. Confirmed that we can no longer push to `main`.
![image](https://user-images.githubusercontent.com/40256709/135935356-f74160ca-3300-433f-aa44-0a3bb6d1498b.png)
